### ISSUE TITLE
Explanation on Prior equation

### ISSUE THREAD

**Issue by doitslow** [StephLong614/Causal-disco-LLM-imperfect-experts#13]
Hi, I spent quite some time reading the paper. Here is my understanding of the idea:
Step1: let expert make decisions on unoriented edges
Step2: as long as p(true graph still in MEC) is in tolerance range and MEC size is large than 1, iteratively do:
for all decisions made by experts:
  1. select a decision 
  2. expand that decision and produce a new MEC
select the decision that produce the MEC which has the smallest size
Step3: consider the final MEC as solution

I am having some trouble understanding the equation for calculating the Prior.   More specifically, what does Ou(MG⋆ )\I = o¬I mean?

**Comment by vzantedeschi** [comment]
Hello!
Exactly, and with have two criteria for selecting a decision. We either select the one the reduces the MEC size the most or the one with the highest posterior probability.

For computing the prior of a subset of orientations O_I, we marginalize over the other orientation variables O_{U(MG⋆ )\I}, hence summing over all their possible value combinations o¬I  .
I think it is easier to read this from the code btw, where we basically count how many times a combination of orientations appear in the MEC (hence in which proportion of graphs): 
https://github.com/StephLong614/Causal-disco-LLM-imperfect-experts/blob/6a5fb05492c385313471a51e26b57c7452812439/models/priors.py#L157

Hope this helps!

**Comment by doitslow** [comment]
Thanks a lot for the quick and detailed reply! Much appreciated.

So, am I right on this? To compute the prior of a subset of orientations O_I, we are essentially doing: given all edges U, for a set of edges I, we consider a set of orientations O_I, and then we count the number of DAGs in the MEC that contain (agree with) O_I. In other words, given O_I, count all the possible orientation combinations of the remaining edges U\I exist in MEC.  (Of course, to get probability, we then divide by MEC size).

**Comment by vzantedeschi** [comment]
exactly! This corresponds to marginalizing as we wrote in the paper.
