### ISSUE TITLE
Algo implementation

### ISSUE THREAD

**Issue by doitslow** [StephLong614/Causal-disco-LLM-imperfect-experts#14]
decision_taken = decision_scores_[0]
        decisions = decision_taken[1]['resulting_decisions']
        mec = [dag for dag in mec if decision_taken[0] in dag]
        p_correct *= decision_taken[1]['probability']

It seems that this chunk of code does nothing in your algo impl. Am I wrong?

**Comment by doitslow** [comment]
decision_scores_ = sorted(decision_scores_.items(), key=lambda item: item[1]['probability'], reverse=False)

Shouldn't reverse=True here?

**Comment by vzantedeschi** [comment]
> ```
>     decision_taken = decision_scores_[0]
>     decisions = decision_taken[1]['resulting_decisions']
>     mec = [dag for dag in mec if decision_taken[0] in dag]
>     p_correct *= decision_taken[1]['probability']
> ```
> 
> It seems that this chunk of code does nothing in your algo impl. Am I wrong?

Hello, these lines update the **mec** list (the set of remaining DAGs,) and the estimated probability of still being correct.
These updates are key to know when to stop or continue the greedy procedure.

**Comment by vzantedeschi** [comment]
> decision_scores_ = sorted(decision_scores_.items(), key=lambda item: item[1]['probability'], reverse=False)
> 
> Shouldn't reverse=True here?

Thank you for spotting this! Indeed it should be reverse=True

**Comment by vzantedeschi** [comment]
Thank you again for spotting this error that was making the greedy selection of orientations more aggressive, hence less performant. We updated the code and are rerunning the experiments. 

We have early results for insurance, which confirms that results are potentially better than what reported in the paper.

**Comment by doitslow** [comment]
@vzantedeschi Great to hear the confirmation on better result with this error fixed!
